# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Detects the host CPU count at workspace-fetch time.

Exposes `NUM_CPUS` (int) and a few precomputed ceilings used for sizing
Verilator and Make parallelism so they adapt to the host rather than
being pinned to a single-site number.

Usage:
    load("@coralnpu_host_cpus//:defs.bzl", "NUM_CPUS", "VERILATOR_THREADS", "MAKE_JOBS")
"""

def _host_cpus_impl(repository_ctx):
    nproc = repository_ctx.which("nproc")
    cpus = 4
    if nproc:
        result = repository_ctx.execute([nproc])
        if result.return_code == 0:
            stripped = result.stdout.strip()
            if stripped.isdigit():
                cpus = int(stripped)

    # Verilator past ~8 threads tends to hit scheduling overhead more than
    # it gains speedup on typical designs; cap to keep runtime sane even
    # on big-iron CI hosts, but never above the host's CPU count.
    verilator_threads = min(cpus, 8)

    # `make -j` for Verilator's generated C++ compile benefits from all the
    # cores it can get. Leave a core for the scheduler on small hosts.
    make_jobs = max(cpus - 1, 1) if cpus <= 4 else cpus

    repository_ctx.file("BUILD.bazel", content = "")
    repository_ctx.file(
        "defs.bzl",
        content = (
            "# Generated by //rules:host_cpus.bzl\n" +
            "NUM_CPUS = {cpus}\n" +
            "VERILATOR_THREADS = {vthreads}\n" +
            "MAKE_JOBS = {mjobs}\n"
        ).format(
            cpus = cpus,
            vthreads = verilator_threads,
            mjobs = make_jobs,
        ),
    )

host_cpus = repository_rule(
    implementation = _host_cpus_impl,
    doc = "Detects host CPU count and exposes parallelism knobs.",
    local = True,
)
